pipeline {
    agent {
        node { label 'build_host' }
    }
    environment {
        CI = 'true'
        DOTNET_RUNNING_IN_CONTAINER = 'true'
    }
    stages {
        stage('Lint') {
            steps {
                sh './jenkins/scripts/lint.sh'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test and Audit') {
            failFast true
            parallel {
              stage('Test') {
                steps {
                    sh './jenkins/scripts/test.sh'
                }
              }
              stage('Audit') {
                steps {
                    sh './jenkins/scripts/audit.sh'
                }
              }
            }
        }
        stage('CodeAnalysis') {
            steps {
                sh 'cd ${PWD}/src; /opt/sonar-scanner-4.2.0.1873-linux/bin/sonar-scanner'
            }
          }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/validate.sh'
                input message: 'Kill the process ? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
