pipeline {
    agent {
        node { label 'build_host' }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Lint') {
            steps {
                sh 'echo "install"'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test and Audit') {
            failFast true
            parallel {
              stage('Test') {
                steps {
                    sh './jenkins/scripts/test.sh'
                }
              }
              stage('Audit') {
                steps {
                    sh 'npm audit'
                }
              }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
